on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: "https://dev-bo.nephroplus.com/"
          parameters:loginRequestBody: "username=dev@focaloid.com&password=test&credentialId="
          loginPageUrl: ""
          loginRequestUrl: "https://dev-bo.nephroplus.com/keycloak/realms/nephroplus/login-actions/authenticate.*"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      # Add additional ZAP jobs here as separate steps
      - name: ZAP Alert Filter
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          type: 'alertFilter'
      - name: ZAP Passive Scan Configuration
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          type: 'passiveScan-config'
      - name: ZAP Spider
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          type: 'spider'
          tests: '[{"onFail": "INFO", "statistic": "automation.spider.urls.added", "site": "", "operator": ">=", "value": 1, "type": "stats", "name": "At least 10 URLs found"}]'
      - name: ZAP SpiderAjax
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          type: 'spiderAjax'
          parameters: '{"maxDuration": 60, "maxCrawlDepth": 10, "numberOfBrowsers": 1}'
          tests: '[{"onFail": "INFO", "statistic": "spiderAjax.urls.added", "site": "", "operator": ">=", "value": 10, "type": "stats", "name": "At least 10 URLs found"}]'
      - name: ZAP Passive Scan Wait
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          type: 'passiveScan-wait'
      - name: ZAP Active Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          type: 'activeScan'
          parameters: '{"policyDefinition": {"rules": []}}'
      - name: ZAP Generate Report
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          type: 'report'
          parameters: '{"template": "risk-confidence-html", "reportDir": "/zap/wrk/", "reportTitle": "ZAP Scanning Report", "reportDescription": ""}'
