name: Send Email via SES

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: Ubuntu 18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        run: |
          mkdir ~/.aws/
          touch ~/.aws/credentials
          chmod 600 ~/.aws/credentials
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=AKIA6LBJHUQAB2EK2YVJ" >> ~/.aws/credentials
          echo "aws_secret_access_key=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" >> ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Send Email via SES
        run: |
          aws ses send-email \
            --from "rijomathew@focaloid.com" \
            --destination "ToAddresses=rijomathew@focaloid.com" \
            --message "Subject={Data=Hello},Body={Text={Data=hello}}" \
            
            
